### ISSUE TITLE
TIL 25/01/21 - Flexbox

### ISSUE THREAD

**Issue by shienka07** [shienka07/AIBE1_TIL#5]
개구리와의 만남은 재밌었지만 사실 아직 **Flex**에 대해서 잘 모르겠다..ㅜㅜ
정말 도움은 많이 됐지만 까먹지 않기위해 오늘은 **Flexbox**

# Flexbox
-  복잡한 계산 없이 요소를 유연하게 정렬하고 배치할 수 있는 모델로, 특히 반응형 디자인에 유용하다
- 주로 **수평** 또는 **수직 방향**으로 아이템을 정렬하거나 분배할 때 사용된다
- 부모 요소(`flex container`)와 자식 요소들(`flex items`)로 구성되며, 부모에서 자식의 배치를 제어한다

<Br>

### 1. display: flex
- **특징**: 
  - 부모 요소에 `display: flex`를 설정하면, 해당 요소는 **flex container**가 된다.
  - 자식 요소들은 **flex items**로 자동 변환된다
- **사용 예시**: 
```css
.container {
    display: flex;
  }
```

### 2. flex-direction
- **특징**: 
   - flex items의 배치 방향을 설정한다
   - `row`, `column`, `row-reverse`, `column-reverse` 값으로 설정 가능하다.
   - `row`가 기본값이다
- **사용 예시**: 

```css
.container {
  flex-direction: row;
}
```

### 3. justify-content
- **특징**: 
    - 메인축을 기준으로 flex items를 정렬한다 - 수평
    -`flex-start`, `flex-end`, `center`, `space-between`, `space-around`, `space-evenly` 값이 있다
- **사용 예시**: 
```css
.container {
  justify-content: center;
}
```

### 4. align-items
- **특징**: 
    - 교차 축을 기준으로 flex items를 정렬한다 - 수직
    - `flex-start`, `flex-end`, `center`, `baseline`, `stretch` 값이 있다
- **사용 예시**: 
```css
.container {
  align-items: center;
}
```

### 5. align-self
- **특징**: 
    - **개별** flex item에 대해 align-items의 정렬을 덮어쓸 수 있다
    - `auto`, `flex-start`,` flex-end`, `center`, `baseline`, `stretch` 값이 있다
- **사용 예시**: 
```css
.item {
  align-self: flex-end;
}
```

### 6. flex-wrap
- **특징**: 
    - flex items가 **한 줄에 배치되지 않을 때**, 줄 바꿈을 허용한다
    - `nowrap`, `wrap`, `wrap-reverse` 값이 있다
- **사용 예시**: 
```css
.container {
  flex-wrap: wrap;
}
```

### 7. flex-grow
- **특징**: 
    - flex item이 남은 공간을 얼마나 차지할지 비율을 설정한다
    - 기본값은 0, 즉 추가 공간을 차지하지 않는다
- **사용 예시**: 
```css
.item {
  flex-grow: 1; /* 여유 공간을 모두 차지 */
}
```

### 8. flex-shrink
- **특징**: 
    - flex item이 공간이 부족할 때 얼마나 줄어들지 비율을 설정한다
    - 기본값은 `1`로, 공간 부족 시 아이템이 줄어든다
- **사용 예시**: 
```css
.item {
  flex-shrink: 0; /* 공간이 부족해도 아이템은 줄어들지 않음 */
}
```

### 9. flex-basis
- **특징**: 
    - flex item의 기본 크기를 설정한다
    - `auto`, `px`, `%` 등의 값으로 지정할 수 있다
- **사용 예시**: 
```css
.item {
  flex-basis: 200px; 
}
```

### 10. order
- **특징**: 
    - flex item의 배치 순서를 지정한다
    - 기본값은 `0`이며, 음수나 양수로 순서를 변경할 수 있다
- **사용 예시**: 
```css
.item {
  order: 2; /* 이 아이템을 뒤로 배치 */
}
```

<br>

# 결론
Flexbox는 요소들을 유연하게 정렬하고 배치하는 데 유용하다. 반응형 디자인에서 특히 유용하며, 복잡한 계산 없이 간단한 속성 설정으로 정렬과 크기 조정을 할 수 있도록 도와준다. 반응형 만들때 알아야하니까 중요!!!!
